미션 0 (맛보기) : 좌표 구하기 단위 테스트
sproutt/heroes2-java-mission1 pull request #2
Opened 2020-08-07 16:34 UTC by GlassK

2020-08-10 16:14 UTC, hyukjin-lee requested changes
고생하셨어요~

2020-08-10 16:14 UTC, hyukjin-lee commented on src/src/CoordinateUnit.java
> +    //좌표 값 하나만 입력하는 경우
스터디 규칙 : 주석이 없어도 쉽게 읽을 수 있는 코드를 지향합니다. (주석은 지양)

2020-08-10 16:14 UTC, hyukjin-lee commented on src/src/CoordinateUnit.java
> +    String isOneValue(String input){
메서드에 접근 제어자를 안 붙이신 이유가 있을까요?

2020-08-10 16:14 UTC, hyukjin-lee commented on src/src/CoordinateUnit.java
> +        if (splitInput.length == 1)
google java convention 을 대부분 따르는데 
{ } 를 생략할 수 있더라도 붙이는 것이 convention 입니다 ~

2020-08-10 16:14 UTC, hyukjin-lee commented on src/src/CoordinateUnit.java
> +    String isValidValue(String input){
'문자열에서 좌표를 추출하는 한가지 행위'만 외부로 노출(public method) 시켜도 되는데
총 세가지로 나누어서 구현하셨네요 :)
public 메서드와 private 메서드의 차이점을 학습해보시면 좋을 것 같습니다 ~

2020-08-10 16:14 UTC, hyukjin-lee commented on src/src/CoordinateUnit.java
> +        String X = splitInput[0].replaceAll("[^0-9]", "");
정규식을 사용하셨네요 ~ 
정규식은 잘 사용하면 편리하고 유용하지만
남용하면 유지보수에 악영향을 끼치니 참고하시면 좋을 것 같아요~ (지금 코드가 그렇다는 뜻은 아닙니다 ~)

2020-08-10 16:14 UTC, hyukjin-lee commented on src/src/CoordinateUnit.java
> +        int intX = Integer.parseInt(X);
int 라는 구체적인 자료형을 나타내는 것보다
number 같은 단어를 사용하는 것이 추후에 자료형이 변경되었을 때
확장성을 가질 수 있는 변수명입니다
참고하시면 좋을 것 같아요~

2020-08-10 16:14 UTC, hyukjin-lee commented on src/src/CoordinateUnit.java
> +    String isValidValue(String input){
is~ 메서드명은 보통 반환값이 boolean 이라는걸 뜻합니다 ~

2020-08-10 16:14 UTC, hyukjin-lee commented on src/src/CoordinateUnit.java
> +            return "Valid numbers range from 1 to 24.";
예외처리를 해보시는건 어떨까요?
조금 버거우시다면 패스 ~

2020-08-10 16:14 UTC, hyukjin-lee commented on src/test/CoordinateUnitTest.java
> +    CoordinateUnit cdn;
스터디 규칙 : 변수명을 줄여쓰지 않는다

2020-08-10 16:14 UTC, hyukjin-lee commented on src/test/CoordinateUnitTest.java
> +        assertThat(result).isEqualTo("x = 1, y = 24");
JUnit 을 처음 써보셨을텐데 잘 쓰셨네요 ~
production code 를 고치시고 
테스트 코드를 조금 고치시면 merge 할 수 있을 것 같습니다

2020-08-12 08:45 UTC, GlassK commented on src/src/CoordinateUnit.java
> +    String isOneValue(String input){
접근 제어자 사용을 염두에 두지 않고 코드를 작성했었습니다! 접근 제어자에 대해 공부해보고 적용해서 반영하겠습니다.

2020-08-12 08:46 UTC, GlassK commented on src/src/CoordinateUnit.java
> +    String isValidValue(String input){
public 메서드와 private 메서드의 차이에 대해 이번 미션을 통해 확실히 짚어볼 수 있을 것 같습니다. 메서드명의 convention에 대해서도 정리해보겠습니다.

2020-08-12 08:47 UTC, GlassK commented on src/src/CoordinateUnit.java
> +        int intX = Integer.parseInt(X);
확장성을 고려한 변수명 짓기에 대해서도 정리해보겠습니다. 감사합니다!

2020-08-12 08:47 UTC, GlassK commented on src/src/CoordinateUnit.java
> +            return "Valid numbers range from 1 to 24.";
그렇지 않아도 예외처리를 잠깐 알아봤었는데 다시 찾아보고 한번 적용해보겠습니다.

2020-08-13 05:27 UTC, merged