Step0 구현 완료
sproutt/heroes2-java-mission1 pull request #3
Opened 2020-08-08 15:00 UTC by vvvpiano

Point클래스와 PointTest 구현했습니다. 피드백 주시면 적극 반영하겠습니다!

2020-08-10 16:25 UTC, hyukjin-lee requested changes
고생하셨습니다~

2020-08-10 16:25 UTC, hyukjin-lee commented on src/main/java/Point.java
> +public class Point {
메서드명이 저같은 영알못에게도 직관적이어서 좋네요 ^^

2020-08-10 16:25 UTC, hyukjin-lee commented on src/main/java/Point.java
> +    String removeParenthesis(String input) {
접근제어자를 생략하신 이유가 있을까요~?

2020-08-10 16:25 UTC, hyukjin-lee commented on src/main/java/Point.java
> +            input = input.substring(1);
google java convention 을 대부분 따르는데  
{ } 를 생략할 수 있더라도 붙이는 것이 convention 입니다 ~

2020-08-10 16:25 UTC, hyukjin-lee commented on src/main/java/Point.java
> +    String getXY (String input) {
이 메서드가 최종적으로 외부에 공개될 메서드이군요~
public, private 접근제어자를 메서드마다 붙여주셨으면
좀 더 읽기 쉬웠을 것 같습니다 ~

2020-08-10 16:25 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        if ((validation = validateNumberArray(pointArr)) != "SUCCESS")
선언과 할당을 분리시키지말고
String validateion = validateNumberArray(pointArr);
로 선언과 할당을 동시에 한 후, if 문에 활용하면 어떨까요?

2020-08-10 16:25 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        }
이 경우에는 i 를 별도로 선언해서 while 문을 쓰는 것보다 for 문이 낫지 않을까요~?

2020-08-10 16:25 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        while (i < 2) {
2 라는 기준이 있는 것 같은데 상수로 추출해서 사용하면 어떨까요?
힌트 : static final

2020-08-10 16:25 UTC, hyukjin-lee commented on src/main/java/Point.java
> +            if (!(1 <= arr[i] && arr[i] <= 24))
중첩조건에 부정이 달려있으면 읽기가 좀 더 어려운 것 같습니다
개선 방안이 있을까요?

2020-08-10 16:25 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        int[] numberArray = new int[stringNumberArray.length];
Array 보다는 Collection(List Map Set) 을 활용해보면 어떨까요?

2020-08-10 16:25 UTC, hyukjin-lee commented on src/test/java/PointTest.java
> +    }
JUnit 사용이 처음이실텐데 구현 잘하셨네요~
getXY() 메서드 하나를 여러 경우의 수로 테스트 한 점 good~

2020-08-11 09:54 UTC, vvvpiano commented on src/main/java/Point.java
> +    String removeParenthesis(String input) {
접근제어자를 유의미하게 사용해본 경험이 없어서 빠트렸네요! 반영하겠습니다!

2020-08-11 09:54 UTC, vvvpiano commented on src/main/java/Point.java
> +        int[] numberArray = new int[stringNumberArray.length];
List 인터페이스를 확장한 ArrayList로 수정 구현했습니다!

2020-08-11 09:54 UTC, vvvpiano commented on src/main/java/Point.java
> +            if (!(1 <= arr[i] && arr[i] <= 24))
(올바른 input을 위한 모든 조건을 충족)이 아닐때 => 저는 개인적으로 이게 더 읽기 편하다고 생각했는데 혹시라도 조건이 늘어나면 더 어려워지고 !이 묻힐수도 있겠네요ㅎㅎ반영하겠습니다!

2020-08-11 09:54 UTC, vvvpiano commented on src/main/java/Point.java
> +        if ((validation = validateNumberArray(pointArr)) != "SUCCESS")
어떤 언어는 선언을 위에서 한번에 미리 한 다음 필요할 때 사용하는 것과, 선언과 할당을 분리할 것을 장려하던데 java에는 적합한 방법이 아닌걸까요?

2020-08-11 10:20 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        if ((validation = validateNumberArray(pointArr)) != "SUCCESS")
js 에서 보통 호이스팅 때문에 선언과 할당을 분리할 것을 장려하는데요,
이는 언어의 특성 때문에 어쩔 수 없는 부분 인 것 같습니다.
스크립트 언어가 아닌 컴파일 언어에서는 선언과 할당을 가능한 분리하지 않거나 가까이에 위치시켜서
해당 변수에 할당된 값이 언제 어떻게 변하는지 한눈에 볼 수 있게하여
버그 유발 가능성을 줄이는 편입니다 ~
그리고 이 코드에서 요구사항이 더 늘어나게 되어 validateNumberArray(pointArr)가 재사용되는 경우가 생긴다면
변수로 결과값을 받아서 그 변수를 활용하여 메서드 호출 횟수를 줄일 수 있고,
validateNumberArray(pointArr)가 재사용되는 경우가 없고 지금처럼 한번만 사용된다면
변수 할당 없이 if (validateNumberArray(pointArr) != "SUCCESS") 로 구현하시는게 불필요한 변수 할당도 없고 좋을 듯 합니다~

2020-08-11 10:21 UTC, hyukjin-lee commented on src/main/java/Point.java
> +            if (!(1 <= arr[i] && arr[i] <= 24))
로버트 C 마틴의 clean code 라는 책에 나오는 부분인데 
절대적으로 강요되는 부분은 아니라고 생각하지만 참고해보는 것도 괜찮을 것 같아요~
https://csharpdeveloper.wordpress.com/2016/01/20/roberts-rules-of-coders-8-avoid-negative-conditionals-and-method-names/

2020-08-11 10:34 UTC, vvvpiano commented on src/main/java/Point.java
> +        if ((validation = validateNumberArray(pointArr)) != "SUCCESS")
스크립트 언어인지 컴파일언어인지의 차이였군요 감사합니다ㅎㅎ피드백 반영했습니다!
그리고 validation != "SUCCESS" 인 경우에는 validation에 담긴 메세지를 출력해야 하기 때문에 이 로직에서는 변수 할당이 필요해 보여서 넣었습니다!

2020-08-11 10:34 UTC, vvvpiano commented on src/main/java/Point.java
> +            if (!(1 <= arr[i] && arr[i] <= 24))
감사합니다!!

2020-08-11 14:40 UTC, hyukjin-lee requested changes
마지막 리뷰입니다 고생하셨습니다

2020-08-11 14:40 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        ArrayList<Integer> numberArray = new ArrayList<>();
조슈아 블로크의 effective java 에는 '객체는 인터페이스를 사용해 참조하라.'
라는 부분이 있습니다.
한번 읽어보시고 개선해보시면 좋을 것 같아요 ~
https://jaehun2841.github.io/2019/03/01/effective-java-item64/#%EC%9C%A0%EC%97%B0%ED%95%9C-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%84-%EC%83%9D%EC%84%B1%ED%95%98%EB%8A%94-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98

2020-08-11 14:40 UTC, hyukjin-lee commented on src/main/java/Point.java
> +        String[] stringNumberArray = input.split(",");
보통 네이밍 할 때 자료형이 드러나는 String, Array 같은 명칭을 지양하는게
추후에 확장성 측면에서 조금 더 이득입니다~ (int -> long, Array -> LinkedList, List -> Set 으로의 요구사항 변경 시)
이 경우에는 numbers or numberTexts 로 표현해도 좋을 것 같네요 ~

2020-08-11 14:40 UTC, hyukjin-lee commented on src/main/java/Point.java
> +    public String getXY (String input) {
실질적으로 중요한 부분인 public 메서드 -> private 메서드 순으로 배치하시면 좀 더 코드를 읽기 편할 것 같습니다 ~

2020-08-11 14:40 UTC, hyukjin-lee commented on src/main/java/Point.java
> +            return validation;
중괄호가 빠졌네요 ~

2020-08-12 14:01 UTC, vvvpiano commented on src/main/java/Point.java
> +        ArrayList<Integer> numberArray = new ArrayList<>();
타입변경이 필요한 상황이나 확장성을 생각하면 뭔가 더 상위클래스를 사용해야 한다는 것만 알았고 인터페이스로는 객체생성이 안된다길래 한참 고민하다가 ArrayList로 참조변수와 객체 모두를 선언했었습니다.  List<> list = new ArrayList<>(); 와 같이 사용하는 예시는 본 적 있는데 이유를 확실히 몰라서 사용하지 않았는데, 올려주신 링크를 보고 확실히 이해되었습니다 감사합니다😄!

2020-08-12 14:04 UTC, vvvpiano commented on src/main/java/Point.java
> +    public String getXY (String input) {
반영했습니다!

2020-08-12 14:05 UTC, vvvpiano commented on src/main/java/Point.java
> +        String[] stringNumberArray = input.split(",");
String과 Array를 자료형의 관점이 아니라 평소에 일반적으로 사용하는 단어라고 생각하고 변수명에 자주 사용하고 있었네요 😅 반영했습니다!

2020-08-13 05:15 UTC, merged