step0
sproutt/heroes2-java-mission1 pull request #4
Opened 2020-08-09 14:07 UTC by asong57

2020-08-10 16:35 UTC, hyukjin-lee requested changes
고생하셨습니다~

2020-08-10 16:35 UTC, hyukjin-lee commented on check.java
> +public class check {
Java 의 Class naming convention 은 맨 앞글자가 대문자입니다 ~
Check 이라는 단어는 메서드(동사)의 의미에 가까운 것 같은데 
문자열에서 좌표를 추출하는 클래스 역할에 맞게 
PointParser, Point 같은 명사로 지어보시면 어떨까요~

2020-08-10 16:35 UTC, hyukjin-lee commented on check.java
> +   static boolean checkXY(String m){
접근제어자를 생략하신 이유가 있을까요?
static 을 붙이신 이유가 궁금합니다 ㅎㅎ

2020-08-10 16:35 UTC, hyukjin-lee commented on check.java
> +   static boolean checkXY(String m){
String m
m 만 봐서는 이 변수가 무슨 역할을 하는지 알 수 없는 것 같습니다.

스터디 규칙 : 모든 변수명은 축약형으로 쓰지 않는다

2020-08-10 16:35 UTC, hyukjin-lee commented on check.java
> +       boolean a;
boolean 메서드, 변수의 naming convention 은 is~~ 입니다.
예 : isValid

2020-08-10 16:35 UTC, hyukjin-lee commented on check.java
> +        int y= Integer.parseInt(xy[1]);;
요구사항에 맞게 ( ) 괄호까지 포함해서 파싱하는 로직이 있어야할 것 같습니다~

2020-08-10 16:35 UTC, hyukjin-lee commented on check.java
> +        }else{a=false;}
글자와 글자 사이의 space, 
줄바꿈 등
모든 것이 가독성을 위해 각 언어마다 convention 이 존재하는데요 ~
intellij 에서는 control+alt+L(window), command+option+L(mac)
단축키를 통해서 reformatting 을 쉽게 할 수 있습니다.
참고해주세요~

2020-08-10 16:35 UTC, hyukjin-lee commented on checkTest.java
> +    }
JUnit 도 처음써보셨을텐데 잘 구현하셨네요 ~
괄호까지 포함해서 파싱 로직 추가하고 테스트 코드도 true, false 만 검증하지 않고
각 상황에 맞는 응답을 받아서 검증할 수 있으면 더욱 좋은 코드가 될 것 같습니다~

2020-08-12 15:08 UTC, asong57 commented on check.java
> +   static boolean checkXY(String m){
접근제어자를 많이 신경쓰지 못해서ㅠ 생략해버렸었네요. 수정하겠습니다!
static을 붙인 이유는 정적인 환경에서 static을 붙이지 않고는 non static 메소드를 사용할 수 없어서 붙였습니다..!

2020-08-12 16:05 UTC, asong57 commented on PointParser.java
> +            //String[] xy = input.split(",");
전의 코드를 잠깐 주석처리해논다는게 깜빡하고 안 지워버렸네요..

2020-08-13 05:25 UTC, hyukjin-lee requested changes

2020-08-13 05:25 UTC, hyukjin-lee commented on checkTest.java
> +        assertTrue(c.checkXY("8,10"));
테스트 코드에 "( )" 괄호가 추가된 케이스가 없는데
잘 돌아가나요?

2020-08-13 05:25 UTC, hyukjin-lee commented on check.java
> +   static boolean checkXY(String m){
메인 메서드를 통한 테스트가 아니라 
JUnit 을 활용해서 테스트 하기 때문에 정적인 환경은 필요없지 않을까요~?

2020-08-13 05:36 UTC, asong57 commented on checkTest.java
> +        assertTrue(c.checkXY("8,10"));
git add가 잘 안 됐나봐요ㅠ 수정된 파일이 안 올라갔네요.. 다시 올리겠습니다!

2020-08-13 05:56 UTC, asong57 commented on check.java
> +   static boolean checkXY(String m){
그렇군요.. static에 대해서 더 공부하고 다음 미션에서 잘 사용해 보겠습니다!

2020-08-13 06:34 UTC, merged