Mission_0
sproutt/heroes2-java-mission1 pull request #5
Opened 2020-08-10 10:27 UTC by kcy13930

피드백 부탁드립니다.

2020-08-10 17:07 UTC, hyukjin-lee requested changes
고생하셨습니다~

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +package Mission_0;
java 의 package 명 convention 은 all 소문자입니다 
참고해주세요 ~

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +public class Coordinate {
클래스명이 간결하고 좋네요 👍

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +        this.y = -1;
-1 을 상수로 빼서 의미를 부여하면 어떨까요?

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +    private boolean isWrongValue(int value){ // 0 이하 25 이상인지 check func
부정형 메서드 보다는 Valid 한 value 를 찾는 긍정형 메서드로 만드는 것이
가독성에 조금 더 이익이 있는 것 같습니다

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +        boolean wrongCase_25 = value>=25;
굳이 boolean 변수로 빼지 않아도 될 것 같습니다.
추출하고 싶으시다면 두가지 조건을 모두를 아우르는 private boolean method 로 wrap 해서 리팩토링 해보시는 것도 괜찮을 것 같네요.
하지만 이정도는 그냥 써도 읽는데엔 문제가 없어보입니다 ~

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +        boolean wrongCase_25 = value>=25;
참고로 java naming convention 은 camelCase 입니다.
snake_case 는 사용되지 않습니다 ~
http://guswnsxodlf.github.io/camelcase-pascalcase-snakecase

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +        if(!isWrongValue(x) && !isWrongValue(y)) {
메서드를 두번 호출하는 것보다 x, y 를 둘다 넘겨서 한번에 처리하는게 낫지 않을까요~?

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +    private void addCoord(int x, int y){ // 이상 없으면 x,y에 값 할당하는 add func
(참고) 이번 스터디는 주석이 없는 코드를 지향합니다

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +        new Coordinate();
오타이신건가요?

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/Coordinate.java
> +    public void coordExtraction(String input) { // 좌표를 추출하는 함수
public -> private 순으로 메서드를 배치하면 더 읽기 좋은 코드가 될 것 같습니다 ~

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/CoordinateTest.java
> +    private void setOneCoord_test(){ // 무작위 값이 하나인 테스트 케이스 func
테스트 코드는 로직에 대한 검증을 테스트하는 것이라
같은 로직을 타는 여러 값에 대한 테스트는 무의미하지 않을까요~?

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/CoordinateTest.java
> +    }
이러한 추상화 메서드들이 가장 중요한 테스트 코드보다 아래에 있는게 순서상 맞는 것 같습니다

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/CoordinateTest.java
> +        setInvalidCoord_test();
모든 테스트 케이스에 대한 초기화를 한 곳에서 해주지 않고
각 테스트 케이스에서 필요한 초기화를 해주면 어떨까요?

2020-08-10 17:07 UTC, hyukjin-lee commented on src/main/java/Mission_0/CoordinateTest.java
> +        negative(noCoord_test);
테스트 코드를 추상화시켜서 단순하게 구현하려고 노력하신 점 👍 
하지만 테스트 코드는 하나의 케이스가 독립적으로 돌아가고,
그 케이스가 깨졌을 때는 빠르게 피드백을 받을 수 있어야합니다.
그러기 위해서는 테스트 코드에 given, when, then 같은
전체적인 테스트의 흐름이 보여야하는데
과한 추상화로 인해 어떤 데이터로 어떤 테스트를 어떻게 진행하는지 알기 어려운 것 같습니다.
우선 정말 변하지 않고 여러 테스트 케이스에서 활용될 수 있는 작은 단위로 메서드 추출을 해보시는게 어떨까요~?

2020-08-10 17:49 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +        this.y = -1;
피드백 반영했습니다.

2020-08-10 17:49 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +    private boolean isWrongValue(int value){ // 0 이하 25 이상인지 check func
피드백 반영했습니다.

2020-08-10 17:49 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +        boolean wrongCase_25 = value>=25;
피드백 반영했습니다.

2020-08-10 17:49 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +    public void coordExtraction(String input) { // 좌표를 추출하는 함수
피드백 반영했습니다.

2020-08-10 17:51 UTC, kcy13930 commented on src/main/java/Mission_0/CoordinateTest.java
> +    private void setOneCoord_test(){ // 무작위 값이 하나인 테스트 케이스 func
(num), (num,), (,num) 모두 따로 테스트해봐야 한다고 생각해서 추가한 함수입니다. 어떤 의미에서 같은 로직을 타는 테스트라 하셨나요? 이해가 안되서요.

2020-08-10 17:51 UTC, kcy13930 commented on src/main/java/Mission_0/CoordinateTest.java
> +    }
피드백 반영했습니다.

2020-08-10 17:57 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +package Mission_0;
피드백 반영했습니다.

2020-08-10 17:57 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +public class Coordinate {
감사합니다~

2020-08-10 17:58 UTC, kcy13930 commented on src/main/java/Mission_0/CoordinateTest.java
> +        negative(noCoord_test);
피드백 반영했습니다.

2020-08-10 18:02 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +        if(!isWrongValue(x) && !isWrongValue(y)) {
한번에 넘기면 오히려 검사하는 함수 코드를 불필요하게 조건문을 두번 짜게 되서 비효율적이라 생각해서 함수 호출 하나 더  추가 하는게 효율적이라 생각하여 이처럼 작성했습니다.

2020-08-10 18:04 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +        if(!isWrongValue(x) && !isWrongValue(y)) {
아 생각해보니 조건문 한번에 가능하군요. 생각이 짧았습니다. 피드백 반영했습니다.

2020-08-10 18:05 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +    private void addCoord(int x, int y){ // 이상 없으면 x,y에 값 할당하는 add func
다음부터 참고하겠습니다.

2020-08-10 18:06 UTC, kcy13930 commented on src/main/java/Mission_0/Coordinate.java
> +        new Coordinate();
새로운 입력이 들어오면 기존 값을 초기화 하는 함수를 새로 짜는 것보다 같은 기능인 생성자 호출해서 초기화 하는게 나을 거 같다고 생각해서 이처럼 추가했는데 좋지 않은 코드면 수정하겠습니다.

2020-08-10 18:15 UTC, kcy13930 commented on src/main/java/Mission_0/CoordinateTest.java
> +        setInvalidCoord_test();
피드백 반영했습니다.

2020-08-10 18:28 UTC, kcy13930 commented on src/main/java/Mission_0/CoordinateTest.java
> +    private void setOneCoord_test(){ // 무작위 값이 하나인 테스트 케이스 func
아 생각이 짧았네요. for문 굳이 3개 안쓰고 한번에 넣으면 되는데 피드백 반영했습니다.

2020-08-11 03:57 UTC, hyukjin-lee requested changes
피드백 빠르게 반영해주시다니 👍 
마지막 피드백 드리고 다음 스텝으로 넘어갈게요 ~

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +    private final int initValue = -1;
각 언어마다 상수 네이밍 컨벤션이 있습니다
java 에서는 ALL 대문자로 표기하고 구분이 필요하다면 _ 로 구분짓습니다 ~

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +        new Coordinate();
이 기본생성자를 호출하면
현재 객체가 초기화 될까요?

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +    public void coordExtraction(String input) { // 좌표를 추출하는 함수
메서드명은 행위를 나타내므로 동사가 적합한데 
extractCoord 어떤가요?

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +        String[] coord_xy = input.split("\\(|,|\\)"); //정규 표현식으로 ( or , or )로 split
camelCase 를 사용하셔야할 것 같습니다 ~
피드백을 부분만 드렸더라도 해당 내용은 코드 전체에 반영해주시면 좋을 것 같아요~

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +            boolean x_notNull = !(coord_xy[1].equals("")); //(,7) 같은 경우 x=""이 되기 때문에 검사
isNullX 정도의 이름이 어떨까요?
대부분 언어에서 boolean 의 네이밍 컨벤션은 is~ 입니다

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +        if(x!=initValue && y!=initValue){
-1을 initValue 라고 칭하니 역할 구분이 어려운 것 같네요.
OUT_OF_RANGE 같은 느낌으로 네이밍 해보시면 어떨까요?

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +        if(x!=initValue && y!=initValue){
코드의 간격, 줄바꿈 등도 컨벤션이 있습니다
intellij 의 reformatting 기능을 사용해서 정렬해보시면 어떨까요?

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +        boolean ValidCase25 = x<25 && y<25;
변수명, 메서드명 camelCase 는 첫글자가 소문자입니다 ~
그냥 써도 충분히 표현 되는 것 같은데 boolean 을 변수로 굳이 받지 않아도 되지 않을까요~?

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/CoordinateTest.java
> +        normalCoordTest();
테스트 메서드명을 통해 이미 이 테스트가 무엇을 수행하는지 설명하고 있는데
같은 이름으로 한번 더 메서드를 추상화 시키면 어떤 이점이 있을까요?

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/CoordinateTest.java
> +        InvalidCoordTest();
메서드명이 대문자로 시작하네요 ~

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/CoordinateTest.java
> +    private void setNormalCoord_case(){ // (1,1~24)~(1~24,1) 모든 일반적인 경우 테스트 케이스 func
해당 로직에 대한 모든 경우의 수를 테스트하지 않으셔도 되지 않을까요~?
(1,1) (1,24) 등 range 에 맞고 2개의 입력을 받는 경우면 모든 케이스가 같은 로직을 타기 때문에
굳이 모든 숫자에 대해 테스트 하실 필요는 없을 것 같습니다 ~
로직을 탔을 때 예상대로 적절한 처리가 이루어져서 예상한 결과값이 나오는지가 테스트 코드의 핵심입니다.

2020-08-11 03:57 UTC, hyukjin-lee commented on src/main/java/mission0/CoordinateTest.java
> +    private void InvalidCoordTest() {
미션 하나 드려볼게요 ~
일단 테스트 클래스에 별도의 private 클래스, 필드 배열 변수들 만들지 마시고
오로지 @Test 메서드만으로 
1. (8,10) 정상case
2. (8,) (,10) (,) invalidInput case
3. (100,0) (1,100) over range case
위 테스트 케이스 세개만 해당 input 으로 간단하게 만들어보시겠어요 ~?

2020-08-11 04:40 UTC, kcy13930 commented on src/main/java/mission0/Coordinate.java
> +    private final int initValue = -1;
넵 참고하겠습니다.

2020-08-11 04:42 UTC, kcy13930 commented on src/main/java/mission0/Coordinate.java
> +        new Coordinate();
네 혹시나 해서 실험해봤는데 초기화 되더라고요. 따로 할당한것도 아니어서 그런지 클래스 내 객체가 호출되고 함수가 static도 아니어서 명령 실행 후에 메모리 내에도 없더라고요.

2020-08-11 04:45 UTC, kcy13930 commented on src/main/java/mission0/Coordinate.java
> +    public void coordExtraction(String input) { // 좌표를 추출하는 함수
oops.. 객체 탐지 인공지능에서 보통 이미지내 객체 위치좌표 검출할때 이런식으로 작성하길래 상관 없는 줄 알았어요. 감사합니다! 연구자들이 작성해 놓은 코드들은 보통 개발쪽에는 어두워서 그런지 모델 결과만 잘나오면 되는지 이런거 무시하더라고요..

2020-08-11 04:46 UTC, kcy13930 commented on src/main/java/mission0/Coordinate.java
> +        String[] coord_xy = input.split("\\(|,|\\)"); //정규 표현식으로 ( or , or )로 split
넵 지적 감사합니다.

2020-08-11 04:46 UTC, kcy13930 commented on src/main/java/mission0/Coordinate.java
> +            boolean x_notNull = !(coord_xy[1].equals("")); //(,7) 같은 경우 x=""이 되기 때문에 검사
넵 피드백 반영하겠습니다.

2020-08-11 04:49 UTC, kcy13930 commented on src/main/java/mission0/Coordinate.java
> +        if(x!=initValue && y!=initValue){
아하 찾아서 해보겠습니다. 감사합니다.

2020-08-11 04:50 UTC, kcy13930 commented on src/main/java/mission0/Coordinate.java
> +        boolean ValidCase25 = x<25 && y<25;
깔끔해 보여서 이렇게 했는데 수정하겠습니다.

2020-08-11 04:53 UTC, kcy13930 commented on src/main/java/mission0/CoordinateTest.java
> +        normalCoordTest();
코드가 길어서 따로 추상화했는데 딱히 네이밍을 어떻게 해야할지 모르겠어서 해당 테스트코드 내용이 담긴 함수라는 의미로 했는데 부적절할까요?

2020-08-11 04:53 UTC, kcy13930 commented on src/main/java/mission0/CoordinateTest.java
> +        InvalidCoordTest();
실수... 수정할게요.

2020-08-11 04:53 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +        new Coordinate();
혹시 실험을 어떤식으로 하셨는지 공유 가능 하실까요~?
기본생성자는 객체 생성시에 자동으로 호출되면서 현재 코드에서는 초기화가 무조건 일어날텐데,
여기서 new Coordinate() 를 하면 그냥 변수로 할당되지 않은 새로운 객체가 생성되고 그게 사용되지는 않을 것 같아서요
실제로 돌려보니 hashcode 값이 다르기도 해서 여쭤봅니다 ~

2020-08-11 04:53 UTC, kcy13930 commented on src/main/java/mission0/CoordinateTest.java
> +    private void setNormalCoord_case(){ // (1,1~24)~(1~24,1) 모든 일반적인 경우 테스트 케이스 func
아하 감사합니다. 반영하겠습니다.

2020-08-11 04:54 UTC, kcy13930 commented on src/main/java/mission0/CoordinateTest.java
> +    private void InvalidCoordTest() {
넵 알겠습니다. 일 끝나고 와서 해보겠습니다.

2020-08-11 04:55 UTC, hyukjin-lee commented on src/main/java/mission0/Coordinate.java
> +    public void coordExtraction(String input) { // 좌표를 추출하는 함수
연구 쪽 개발과 비즈니스 쪽 개발이 중요시 하는 부분은 확실히 차이가 날 수 밖에 없을 것 같아요 ㅎㅎ
그럼에도 불구하고 스터디 과정을 수행하시는 Window0 님께 리스펙을 표합니다 !

2020-08-11 04:55 UTC, kcy13930 commented on src/main/java/mission0/Coordinate.java
> +        new Coordinate();
일 끝나고 와서 올릴게요.

2020-08-12 09:48 UTC, kcy13930 commented on src/main/java/mission0/Coordinate.java
> +        new Coordinate();
제가 헛것을 봤나 봅니다;; 다시 테스트 하니 안되서 초기화 하는 함수 따로 만들었습니다.

2020-08-13 05:14 UTC, merged