[미션 1] 구현 완료했습니다. 리뷰 요청드립니다
sproutt/heroes2-java-mission1 pull request #6
Opened 2020-08-17 19:55 UTC by vvvpiano

어려웠던점

- 커스텀 exception을 통한 예외처리 시도
- private method를 테스트하는 것
- 위의 두가지로 인해 발생한 다양한 상황들 => private method를 테스트하기 위해 사용하는 invoke함수가 내 커스텀 exception을 InvocationTargetException으로 감싸서 예외를 던지는 바람에 내가 의도한대로 테스트가 작동하지 않아서 원인을 찾는데 오래걸렸다. 그리고 InvocatoinTargetException으로 감싸졌기 때문에 [원래 쓰려고 했던 expected exception을 통한 예외테스팅 방법](https://rightnowdo.tistory.com/entry/JAVA-JUnit%EC%97%90%EC%84%9C-%EC%98%88%EC%99%B8-Test%ED%95%98%EA%B8%B0)을 사용해보지 못했다. (아직 이 도구가 익숙하지 않아서 적절한 방법을 찾지 못한걸 수도 있다.)
- while문 안에서 try-catch를 쓰면 인덴테이션이 2가 되는 문제 때문에 고민하다가 어쩔수 없이 재귀호출을 사용해야 했던 점
InputView클래스에서 차 이름, 실행 횟수를 받는 기능을 모두 만들다가 예외처리 코드때문에 점점 클래스 길이가 길어져서 두 클래스로 쪼개야 했음
- 역시 인덴테이션을 줄이기 위해서 필터 기능을 위해 stream()메소드를 처음 활용해 보았음.
- nextInt에 문자를 입력했을 경우 발생하는 InputMismatchException을 테스트하기 위해서 Input클래스를 생성할 때 System.in이 들어갈 자리를 InputStream형 매개변수로 분리해내서 ByteArrayInputStream으로 직접 문자열을 주어서 테스트 할 수 있도록 시도했음.

알고리즘은 크게 어렵지 않다고 생각했는데, 나름 깔끔한 객체를 위해 설계하는 시간이 오래걸렸다. 그리고 익숙하지 않은 예외처리와 다양한 테스트 메소드들을 찾아보고 활용해 보는데 시간과 노력을 썼던것 같다.

2020-08-19 17:09 UTC, hyukjin-lee requested changes
description 도 좋고
코드도 첫 정식 과제인데 너무 잘하셨네요
피드백 조금 남겼으니 궁금한 점은 질문해주시고
반영 끝나시면 말씀해주세요 ~

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/Car.java
> +    public int compareTo(Car car) {
Comparable 을 구현해서 collection sort 를 활용하셨군요 ~
만약 시스템이 더 커지고 요구사항이 늘어나서 Car 라는 model을 다른 곳에서 다른 방식으로 정렬할 경우가 생길 수도 있는데
그런 경우에 Car 에서 공통적인 정렬 기준을 가지고 있으면 어떤 문제가 생길까요?

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/Car.java
> +    private char carChar;
carChar 은 프로그램의 요구사항에 따라 '-' 이 될 수도 있고
'~' 이 될 수도 있고 변화의 여지가 많은 값인 것 같습니다.
필드 변수로 가지고 있을 필요가 있을까요?
자동차라는 모델 클래스보다는 게임을 진행을 담당하는 클래스에서 상수로 들고 있으면 어떨까요?

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/Car.java
> +    private static final int MAX_POWER = 10;
자동차 모델이 게임의 룰을 알고 있는 것보다, 게임을 진행하는 클래스에서 해당 내용들을 알고 있는게 어떨까요?

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/Car.java
> +        this.position = position;
규칙 : setter 를 사용하지 않는다 (getter 사용은 지양한다)

객체지향 프로그래밍에서 setter 와 getter 사용을 되도록 지양하라고 하는 이유가 무엇일까요?

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/Car.java
> +            this.setPosition(this.getPosition() + 1);
랜덤을 통해 특정 조건에서 전진하는 게임의 룰을 자동차라는 모델 클래스가 알고 있을 필요가 있을까요?
예를 들어 게임의 모드가 추가되어서 랜덤 룰이 아닌 다른 게임 룰이 생긴다고 했을 때,
모델이 게임의 룰에 관계없이 pure 하게 짜여져 있으면 모델을 수정하지 않아도 되지 않을까요?
moveForward 가 단순히 car 의 position 을 ++ 하는 로직만 가지고 있으면 어떤지 의견드려봅니다 ~

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/InputCarName.java
> +public class InputCarName {
InputCarName, InputCount
모두 InputView 의 관심사이기 때문에 
한 클래스의 메서드로 표현되어도 될 것 같은데 분리하신 이유가 있나요~?

2020-08-19 17:09 UTC, hyukjin-lee commented on src/test/java/InputCarNameTest.java
> +            Method checkLengthLimit = inputCarName.getClass().getDeclaredMethod("checkLengthLimit", String.class);
private method 를 테스트하려고 노력하셨군요~ 👍 

그러나 public 과 private method 의 의미에 대해서 좀 더 생각해본다면 

private method 를 테스트할 필요가 있을까요?

관련해서 도움이 될 만한 자료 첨부드립니다
https://blog.benelog.net/2685835.html

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/RacingView.java
> +        System.out.println(winnersWithCommas + "가 최종우승 했습니다.");
java 8 stream api 를 적용해보기 좋은 코드인 것 같습니다
한번 고쳐보시는걸 추천드립니다 !

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/Main.java
> +        }
이름을 받아서 자동차 생성하는 로직은 RacingGame 에서 차량 세팅하는 메서드를 만들어 위임하면 어떨까요?

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/InputCarName.java
> +            carNames = this.parseString(value);
내부 메서드 호출할 때 this 안쓰셔도 됩니다 ~

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/InputCount.java
> +        }
재시도 로직을 포함하려고 하신 점 👍 
하지만 이번 과정에서는 재시도 말고 그냥 잘못된 입력에 대해서는 에러 던지고 끝내면 어떨까요? (모든 부분에서)

이유는 크게 없고 요구사항을 제한시켜서 코드 짤 때 이런 부분에 대한 고민을 좀 줄여드리고 싶어서요 ~

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/InputCount.java
> +            throw new InputViewException("[Error] 시도 회수는 0보다 커야 합니다");
중괄호가 생략되었습니다

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/InputView.java
> +        return count;
return 한줄로 가능하겠네요 ~

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/InputView.java
> +        InputCount inputCount = new InputCount(System.in);
사용자들에게 입력 받을 때 마다 InputCount 객체가 생성되는 것 같은데
메모리 측면에서 낭비가 아닐까요~?
Input 관련, Output 관련은 static 한 utility 클래스들로 만들어서 객체 생성을 줄여보면 어떨까요?

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +    private RacingView racingView;
RacingGame 에서 View 에 의존성이 생기지 않도록 개선해보면 어떨까요?

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +        this.racingView.showWinner(this.findWinner());
this 를 사용하지 않으셔도 됩니다.
this 는 파라미터와 필드 변수가 같은 이름을 사용하는 경우에 사용하시면 됩니다 ~

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +    public void run() {
메서드에 포함된 일련의 과정에서 View 에 대한 부분은 Main 에 위임시켜보면 좋을 것 같습니다

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +            System.out.println();
System.out 같은 View 에 관련된 행위가 이곳에 있으면 어떤 문제가 발생할까요?
이 게임이 콘솔이 아니라 GUI 환경에서 돌아가도록 요구사항이 변경된다고 했을 때,
view 역할에 해당하는 클래스가 아닌 곳에서 console 과 연관된 코드가 있으면
변경이 힘들어질 수 있지 않을까요~?

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +        List<Car> filteredCars = new ArrayList<Car>();
이곳에서 불필요한 초기화가 이루어져서 메모리가 낭비되고 있습니다 ~

2020-08-19 17:09 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +        return filteredCars;
return Cars.stream()
           .filter(isSamePosition(position))
           .collect(Collectors.toList());

한방 return 으로 개선할 수 있겠네요 ~

2020-08-20 12:55 UTC, vvvpiano reviewed
개인적으로 문제를 조금 다른 방향으로 이해하고 코드를 짠것 같다고 생각이 드네요ㅎㅎㅠ 궁금한 점이 많은데 시간 날 때 읽어보시고 답변해주시면 감사하겠습니다!

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/Car.java
> +    private char carChar;
THRESHOLD, MAX_POWER, carChar 모두 Car의 필드 변수로 둔 이유는 이 요소들을 **게임의 규칙이 아니라 자동차의 성능이라고 생각**했기 때문입니다! 지금은 Car클래스에 각각의 변수들에 대한 setter들이 없긴 하지만 사용자가 자신의 차를 어떤 문자 모양으로 나타낼지(carChar) 나중에 커스텀을 할 상황을 상상했습니다. 그리고 만약 자동차를 업그레이드시킨다면 THRESHOLD를 낮추거나 MAX_POWER를 높여서 각 자동차가 전진할 확률을 더 높임으로써 그 사용자의 자동차가 승리하기에 더 유리하게 만들 수 있을것 같습니다. 사용자가 자신의 자동차를 원하는대로 설정하고, 경험치를 높여서 다른 사람들을 이기는게 게임의 필수 요소로 생각해서 이렇게 설계했습니다ㅎㅎ

미션의 기능요구사항에서 전진조건을 **레이싱 게임의 규칙 관점**으로 생각한다면 잠만보님께서 말씀해주시것처럼 게임이 가지고 있어야 하는 정보인것 같다는 생각이 드네요! 혹시 위의 설명처럼 제가 생각한 점들이 코드에 설득력을 조금 더 더해줄지 모르겠습니다! 어떻게 생각하시나요? 😄

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/Car.java
> +        this.position = position;
객체의 외부에서 객체의 데이터를 직접 다루면 나중에 객체에 변경사항이 생겼을 때 데이터에 의존된 코드들도 바꿔야 하는 일들이 발생하기 때문이라고 알고있습니다! 이부분은 삭제하고 기능구현을 수정해보겠습니다ㅎㅎ

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/Car.java
> +            this.setPosition(this.getPosition() + 1);
위에서 설명드렸던것과 같은 이유로 이렇게 코드를 짰습니다. 제가 의도와 조금 다르게 미션을 이해한것 같네요!! 🤔 좀더 고민해보고 근본적인 게임규칙에 따라 수정이 필요하다면, 반영해보도록 하겠습니다!

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/Car.java
> +    public int compareTo(Car car) {
그런 상황도 있을수 있겠네요! 그런 상황도 고려해서 수정해보도록 하겠습니다!

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/InputCarName.java
> +public class InputCarName {
말씀하신것처럼 InputView하나에 두 로직을 모두 넣었었는데 예외처리하다가 클래스가 너무 길어져서 쪼갰습니다! 말씀하신대로 잘못된 입력에 대해 예외를 던지고 바로 프로그램 종료하도록 로직을 수정한다면 InputView하나로 합칠수 있을것 같습니다!

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/InputCarName.java
> +            carNames = this.parseString(value);
넵!ㅎㅎ javascript랑 헷갈렸네요ㅎㅎㅎㅎ

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/InputCount.java
> +        }
ㅎㅎ알겠습니다! 반영하겠습니당

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/InputView.java
> +        InputCount inputCount = new InputCount(System.in);
반영해보겠습니다!

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/Main.java
> +        }
이것도 위에서 말씀드린 이유와 같은데ㅎㅎㅎ제가 게임을 너무 복잡하게 생각했나봐요! 메인의 예시 코드로는 모두 같은 setting값의 자동차들이지만, 각자 다른 setting값으로 커스텀 된 자동차들이 레이싱게임에 입장하는 상황을 상상하고 밖에서 car객체를 만들어 RacingGame에 넣도록 만들었습니다. 이런 로직이 필요없다면 RacingGame안에 포함시킬수 있을 것 같습니다ㅎㅎ

2020-08-20 12:55 UTC, vvvpiano commented on src/main/java/RacingGame.java
> +    private RacingView racingView;
저도 그 부분을 고민 많이했는데, n번동안 전진 한번씩 할 때마다 출력을 해야 해서 RacingGame안에 View클래스를 넣었네요ㅎㅎ n번 전진 로직을 main으로 빼는건 어색하지 않을까요? 게임 진행 시간동안 자동차들을 주행시키는건 게임클래스의 몫인것 같기 때문입니다. 아니면 자동차들을 n번 전진시키는건 RacingGame클래스 내에서 함과 동시에 View클래스를 밖으로 빼서 과정을 다 출력할 수 있는 방법이 있을까요?

2020-08-20 12:55 UTC, vvvpiano commented on src/test/java/InputCarNameTest.java
> +            Method checkLengthLimit = inputCarName.getClass().getDeclaredMethod("checkLengthLimit", String.class);
모든 로직을 테스트 해야한다고 해서 private도 테스트해야하나 고민이 많았는데, 첨부해주신 자료를 보니까 

> 하지만 private method를 public에서 간접적으로 테스트하는 것만으로 충분하지 않고 따로 테스트를 해봐야할 정도가 된다는 것도 설계 개선의 신호일 수 있습니다.

이 말에 무릎을 치고 갑니다!

2020-08-23 15:43 UTC, hyukjin-lee commented on src/main/java/Car.java
> +    private char carChar;
WOW 설득이 충분히 되었습니다 !
저는 개인적으로 좋은 코드란 개발자의 고민이 담긴 코드라고 생각합니다. 그런 의미에서 정말 좋은 코드를 짜셨네요 ~

덕분에 미션 요구사항에 대해 이렇게 생각할 수도 있다는 점에 대해 알 수 있게 되었습니다
감사합니다 ~ :) 🥇 

(자동차의 성능을 관리하는 객체를 설계 해볼 수도 있지 않을까. 이런 고민도 해보시면 좋을 것 같아요 ~)

2020-08-23 15:47 UTC, hyukjin-lee commented on src/main/java/Car.java
> +    private char carChar;
자료형이 드러나는 carChar 보다 자동차의 모양? 같은 뜻을 나타내는 shape 는 어떤가요?

그리고 shape 가 콘솔에서는 -, ~ 등으로 표현될 수 있지만 view 가 여러종류(gui, app, web 등)일 경우에 숫자 코드값으로 저장되고 view 에서 번호에 따라 어떻게 그릴지 결정하는 책임을 가지도록 설계하는 것도 좋을 것 같네요 ~

2020-08-23 16:05 UTC, hyukjin-lee commented on src/main/java/Main.java
> +        }
Main 은 다른 객체들에 일을 시키는 정도의 역할만 하도록 하는게 나을 것 같아요 ~
RacingGame 에서 게임을 start 하기 위해서는 말씀대로 사전에 setting 을 해야하는데
입장을 한다기보다 RacingGame 이라는 객체에서 차량 세팅까지 책임져야한다고 생각해보시면 어떨까요?
setting에 커스텀 조건들이 있으면 해당 조건들도 메서드의 파라미터로 넘기면 될 것 같아서요 ~

2020-08-23 16:05 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +    private RacingView racingView;
여태 과정하면서 Main 으로 빼서 n번 돌리는 분들도 많았는데 구름님 말씀처럼 RacingGame 의 역할이라고 보는게 맞죠.
RacingHistory 클래스를 만들어보시면 어떨까요?

2020-09-02 02:59 UTC, hyukjin-lee approved these changes
피드백 한번에 코드가 많이 달라지셨네요

바로 머지해도 되겠습니다

고생 너무 많으셨어요 ~

2020-09-02 02:59 UTC, hyukjin-lee commented on src/main/java/util/InputView.java
> +        scanner = new Scanner(inputStream);
Scanner 를 매번 생성하기엔 비용이 좀 큰 것 같습니다.
Main 에서 Scanner 를 View 메서드에 파라미터로 넘겨주면 어떨까요?

2020-09-02 02:59 UTC, hyukjin-lee commented on src/main/java/util/RacingView.java
> +public final class RacingView {
class 에 final 을 붙이신 이유는 무엇인가요~?

2020-09-02 02:59 UTC, merged

2020-09-02 04:48 UTC, vvvpiano commented on src/main/java/util/RacingView.java
> +public final class RacingView {
util클래스의 예시들을 보니까 클래스 앞에 final을 붙이고 메소드에 static을 붙이는 경우가 많더라구요. util클래스면 final로 선언하는게 말이 되겠다~ 생각하고 따라서 붙였는데 피드백 보고 찾아보니까 나중에 이 클래스를 상속하거나 오버라이딩이 안된다고 하네요! final키워드는 굳이 없어도 될 것 같습니다!

2020-09-02 04:48 UTC, vvvpiano commented on src/main/java/util/InputView.java
> +        scanner = new Scanner(inputStream);
피드백 반영해보겠습니다!

2020-09-02 04:54 UTC, vvvpiano commented
아마 1차 피드백 후에 필요한 클래스들을 추가하다가 패키지를 나누어서 파일 위치가 옮겨져서 이전버전에 비교해 수정된 부분을 파악하기 어려우셨을 것 같습니다!ㅠㅠ 1차 피드백 반영 후 PR description을 추가했는데, CarStamp나 RacingStamp 측면에서 이렇게 구현하는게 맞나?싶으면서 했던 고민들을 적어두었습니다. 시간이 괜찮으실 때 천천히 의견 적어주시면 감사하겠습니다!!

2020-09-02 05:47 UTC, hyukjin-lee reviewed
description 고민들을 읽고 추가 피드백 남겨보아요~

2020-09-02 05:47 UTC, hyukjin-lee commented on src/main/java/domain/RacingGame.java
> +    private List<String> carNames;
racingCars 로 부터 추출될 수 있는 데이터는 필드로 갖고 있지 않아도 되지 않을까요~?

2020-09-02 05:47 UTC, hyukjin-lee commented on src/main/java/domain/RacingGame.java
> +    private RacingHistory history;
List<List<CarStamp>> -> List<RacingStamp> -> RacingHistory 으로 감싸졌군요

Description 에 적어주신 고민에 대한 부분은 DTO 와 VO 에 대해 공부해보시면 좋을 것 같습니다.
https://makemethink.tistory.com/168

js 같은 경우는 json 을 그 자체로 편하게 다룰 수 있는 랭귀지지만
java 같은 경우에는 그러한 데이터도 클래스로 매핑 시켜 코드를 짜야하는 경우가 대부분입니다.

객체지향에서는 객체가 책임을 갖고 있는 행위와 그 행위에 따르는 상태를 해당 객체가 가지고 있는 것을 지향하는데요,
이 지향점만으로는 수많은 외부의 변화들과 요구사항들을 수용할 수 없기 때문에 데이터를 담는 역할만 하는 객체라는 개념도 생기고
상태가 없는 객체가 생길 수 있고, 등등 여러 상황에 대한 트레이드 오프로 인해 생긴 개념들이 많이 있습니다.
(지금 과정에서는 객체지향을 학습하는 것이기 때문에 불필요하게 발생한 트레이드 오프를 지양하는 코드로 리뷰를 하고 있습니다)

저는 CarStamp와 RacingStamp 를 일종의 VO 로 보고 RacingHistory 는 write 라는 행위를 지니고 있는 히스토리 담당 비즈니스 도메인 객체라고 이해해보았습니다. 제가 보기엔 좀 더 개선할 여지는 있겠지만 이 단계에서는 충분히 좋은 코드인 것 같아요~

2020-09-02 05:47 UTC, hyukjin-lee commented on src/main/java/domain/RacingGame.java
> +    public void run() {
void 에 대한 테스트는 해당 메서드를 실행해서 변경된 데이터를 getter 를 통해 검증하는 방법이 있을 것 같습니다 ~