Step1
sproutt/heroes2-java-mission1 pull request #8
Opened 2020-08-19 09:25 UTC by kcy13930

늦게 해서 죄송합니다;;

2020-08-23 03:18 UTC, hyukjin-lee requested changes
고생하셨습니다 ~
처음이신데 잘 구현해주셨네요 !
피드백 조금 남겼으니 확인 후 반영해주시면 감사하겠습니다
미션 규약과 과제들을 한번 더 살펴보시는 것도 좋을 것 같습니다~

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +    private ArrayList<Integer> carPosition = new ArrayList<>();
바로 위에 car 리스트를 통해 car position 을 추출할 수 있어서 상태값으로 가지고 있지 않아도 되지 않을까요?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +    private ArrayList<String> car = new ArrayList<>();
생성자가 아니라 필드에서 초기화를 하신 이유가 있으실까요?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +    private ArrayList<String> car = new ArrayList<>();
조슈아 블로크의 effective java 에는 '객체는 인터페이스를 사용해 참조하라.'
라는 부분이 있습니다.
한번 읽어보시고 개선해보시면 좋을 것 같아요 ~
jaehun2841.github.io/2019/03/01/effective-java-item64/#%EC%9C%A0%EC%97%B0%ED%95%9C-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%84-%EC%83%9D%EC%84%B1%ED%95%98%EB%8A%94-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +    private ArrayList<String> car = new ArrayList<>();
네이밍이 복수형이어야 할 것 같습니다 car -> cars

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +    public void setCar(String input){
단순히 setter 동작을 하는게 아니라서 추후에 유지보수 과정에서 헷갈릴 여지가 있을 것 같습니다 
setCar(String input) -> readyForStart(String carNamesText) 는 어떨까요?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +            }
indent 가 2네요. 미션 제한사항을 지켜주시면 좋을 것 같아요 ~

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +            if(condition >= 4 && condition <= 9){
4, 9 가 어떤 의미를 지니고 있는지 2년 뒤에 이 코드를 보거나 타인이 보면 이해가 잘 안될 수 있을 것 같아요.
이런 magic number 를 상수로 추출해보는게 어떨까요?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +    public String winner(){
메서드 명이 명사네요~

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +        Integer maxValue = (Integer) Collections.max(carPosition);
maxValue -> maxPosition 이 어떨까요?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +        ArrayList<String> winner = new ArrayList<>();
winner -> winners 는 어떨까요?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGame.java
> +            }
여기도 indent 2 네요 ㅠㅠ

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/Main.java
> +package MISSION_1;
패키지 명은 all 소문자로 해주셔야 합니다 ~

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGameTest.java
> +package MISSION_1;
src/test/java/ 경로에 테스트 클래스를 만드셔야해요.
테스트 코드가 프로덕션 코드와 같이 패키징되면 어떤 문제가 있을까요?


(intellij 에서 테스트 클래스를 자동으로 만들어주는 단축키가 있는데
그걸 사용하시면 편할거에요 ~)

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGameTest.java
> +        }
move 메서드를 어떻게 테스트하고 있는건지 설명가능하실까요?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/View/InputView.java
> +    private int time;
inputView, outputView 에는 상태를 가지지 않는 util 성 클래스로 동작할 수 있도록
상태를 없애보시면 어떨까요~?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/View/InputView.java
> +    public int getTime() {
getter 는 상태가 없어질 이곳에서 필요 없을 것 같아요 ~ 메서드와 반환값을 적절히 잘 사용해보시면 어떨까요~

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/View/ResultView.java
> +        }
view 에 비즈니스 로직이 들어가지 않도록 다시 설계해보시면 어떨까요?
추후에 콘솔로 입출력이 이뤄지던 게임이 GUI 로 요구사항이 확장된다고 가정 했을 때,
비즈니스로직이 view 에 있음으로써 재사용이 불가능해지고 중복코드가 늘어나지 않을까요~?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/View/ResultView.java
> +    RacingGame car;
이전 클래스 피드백과 동일하게 view 에서는 상태를 가지지 않는게 어떨까요

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/View/ResultView.java
> +            car.move();
자동차가 움직이는 행위는 아주 중요한 게임의 진행요소인데 view 에 숨어있었네요
Main 에서 일련의 과정이 보이도록 설계해보시면 어떨까요?

2020-08-23 03:18 UTC, hyukjin-lee commented on src/main/java/mission_1/View/InputView.java
> +        time = scanner.nextInt();
생성자에서 이러한 행위들을 수행하면 어떤 점이 안좋을까요?

2020-08-23 11:31 UTC, kcy13930 commented on src/main/java/mission_1/RacingGame.java
> +    private ArrayList<Integer> carPosition = new ArrayList<>();
반영하겠습니다.

2020-08-23 11:31 UTC, kcy13930 commented on src/main/java/mission_1/RacingGame.java
> +    private ArrayList<String> car = new ArrayList<>();
swift 스터디에서 생성자에서 초기화 했다가 고정된 값은 필드에서 하는게 좋다고 해서 별 상관 없을거라 생각했는데 고치겠습니다.

2020-08-23 11:32 UTC, kcy13930 commented on src/main/java/mission_1/RacingGame.java
> +    public void setCar(String input){
반영하겠습니다.

2020-08-23 11:34 UTC, kcy13930 commented on src/main/java/mission_1/RacingGame.java
> +            }
분리하겠습니다.

2020-08-23 11:34 UTC, kcy13930 commented on src/main/java/mission_1/RacingGame.java
> +            if(condition >= 4 && condition <= 9){
반영하겠습니다.

2020-08-23 11:37 UTC, kcy13930 commented on src/main/java/mission_1/RacingGameTest.java
> +        }
랜덤값(0 ~ 9)이 들어왔을때 4 ~ 9면 증가하니 1, 0~3이면 0으로 테스트 했습니다.

2020-08-23 11:37 UTC, kcy13930 commented on src/main/java/mission_1/View/InputView.java
> +    private int time;
피드백 반영하겠습니다.

2020-08-23 11:40 UTC, kcy13930 commented on src/main/java/mission_1/View/ResultView.java
> +        }
처음에 그렇게 구현했다가 View가 로직에서 데이터를 받아서 보여주는 기능을 하니 view의 영역이라 생각해서 이렇게 구현했습니다.

2020-08-23 11:40 UTC, kcy13930 commented on src/main/java/mission_1/View/ResultView.java
> +    RacingGame car;
반영하겠습니다.

2020-08-23 11:41 UTC, kcy13930 commented on src/main/java/mission_1/View/ResultView.java
> +            car.move();
반영하겠습니다.

2020-08-23 11:45 UTC, kcy13930 commented on src/main/java/mission_1/View/InputView.java
> +        time = scanner.nextInt();
객체 정보가 드러나는 거 같습니다. scanner를 따로 Main으로 빼서 입력 받겠습니다.

2020-08-23 11:46 UTC, kcy13930 commented on src/main/java/mission_1/View/InputView.java
> +    public int getTime() {
반영하겠습니다.

2020-09-08 07:48 UTC, hyukjin-lee approved these changes
고생하셨습니다 ~

2020-09-08 07:48 UTC, hyukjin-lee commented on src/main/java/mission_1/RacingGameTest.java
> +            assertEquals(0, (int) carInfo.get(car));
move 만 독립적으로 테스트할 수 있도록 변경해보면 좋을 것 같네요.
지금은 테스트코드에 로직이 들어가있어서 걷어내야할 것 같습니다

2020-09-08 07:48 UTC, merged